name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or your default branch name

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: email-bot
  REGION: asia-south1
  REPOSITORY: email-bot

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev

    - name: Build and Push Container
      run: |
        docker build -t asia-south1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/email-bot:${{ github.sha }} .
        docker push asia-south1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/email-bot:${{ github.sha }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: asia-south1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/email-bot:${{ github.sha }}
        flags: '--allow-unauthenticated'
        env_vars: |
          EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAILS=${{ secrets.RECIPIENT_EMAILS }} 